language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install .
  - pip install sphinx
  - pip install git+https://github.com/miyakogi/m2r.git
script:
  - cd docs
  - sphinx-build -b html -d _build/toctree -E -W . _build/html
